# Generated by Django 5.1.4 on 2024-12-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='cuctomer',
            new_name='customer',
        ),
    ]
