# Generated by Django 5.1.4 on 2024-12-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='producut',
            new_name='product1',
        ),
    ]
