# Generated by Django 5.1.4 on 2024-12-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_producut_wishlist_product1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product1',
            new_name='wishlist',
        ),
    ]
