# Generated by Django 5.1.4 on 2024-12-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_product1_wishlist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist',
            new_name='product',
        ),
    ]
